version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: lagnarok.sln
  verbosity: minimal
artifacts:
- path: lagnarok.dll
deploy:
- provider: GitHub
  auth_token:
    secure: yNUbKU1WhU2hfNQsbBhIhq4xBdfcGX944mppUYnp+qX/xlpmnEYwWohxwW8DYLc8
  artifact: '*.*'
  force_update: true
